name: Kernel NuGet Release

on:
  release:
      types: [published]

jobs:
  publish-nuget:

    runs-on: windows-latest

    name: Publish NuGet Release
    steps:

    - name: Get Version
      id: version
      uses: battila7/get-version-action@v2

    - name: Test Version
      run: echo ${{ steps.version.outputs.version-without-v }}
            
