name: Kernel CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths-ignore:
    - "**/.github/**"
    - "**/.editorconfig"
    - "**/README.md"
    - "**/templates/**"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore

    - name: Get Version
      id: version
      uses: battila7/get-version-action@v2
      
    - name: Build
      run: dotnet build -c Release --no-restore -p:Version=${{ steps.version.outputs.version-without-v }}
      
    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal --filter "FullyQualifiedName!~Integration"

    - name: 'Pack project'
      run: dotnet pack ${{ env.PROJECT_PATH }} --no-restore --no-build --configuration Release --include-symbols -p:PackageVersion=${{ steps.version.outputs.version-without-v }} --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}            
